### ISSUE TITLE
Problem Loading the torch file

### ISSUE THREAD

**Issue by paidiakileswar** [vishalsharbidar/SphereGlue#10]
I done the steps ->

`pip -r install requirements.txt`

```

And ran the superscript ->

(sphereglue) ubuntu@ml-ultra-high-spot-04:~/workdir/akil/SphereGlue$ python demo_SphereGlue.py --save_npz True --draw_matches True --display_matches True

args Namespace(input='data/', output='output', matches='matches/', images='images/', match_threshold=0.2, batch_size=1, max_kpts=20000, knn=20, sinkhorn_iterations=20, aggregation='add', force_cpu=False, detector='superpoint', save_npz=True, draw_matches=True, display_matches=True)

Running inference on device "cuda"
Size of Dataset 5
Traceback (most recent call last):
  File "/home/ubuntu/workdir/akil/SphereGlue/demo_SphereGlue.py", line 89, in <module>
    ckpt_data = torch.load(model_path)
  File "/home/ubuntu/conda/envs/sphereglue/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/conda/envs/sphereglue/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```

@vishalsharbidar @vishalsharbidar @vishalsharbidar

**Comment by paidiakileswar** [comment]
Solved ->

By commenting `torch.load` line in code
