### ISSUE TITLE
Problem Loading the model

### ISSUE THREAD

**Issue by Luffy2810** [vishalsharbidar/SphereGlue#9]
When I try to load the model I am faced with the following error:

Traceback (most recent call last):
  File "/workspace/sahil/colmap/SphereGlue/demo_SphereGlue.py", line 89, in <module>
    ckpt_data = torch.load(model_path)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/opt/conda/lib/python3.10/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by loffermann** [comment]
Hi, I have been facing the same problem. The error occurs because model weights are stored using git-lfs. If git-lfs is not installed on your system, the files for the model weights remain text files and do not get resolved to the actual snapshots. To mitigate, install git-lfs on your system, then run git lfs pull (see https://github.com/git-lfs/git-lfs/issues/325).

**Comment by EnriqueSolarte** [comment]
Yes, I confirm the issue and the solution. Thanks @loffermann. 
```shell
sudo apt-get install git-lfs
cd ${SphereGlue_Dir}
git lfs pull
```

**Comment by vitusleng** [comment]
@EnriqueSolarte @loffermann  @Luffy2810  The model weights seems cannot be downloaded due to lfs budget issue, if you saved it, would you please share a link to download them?
